Repository PennLINC/aslprep, pull requests merged in 2023-02, with the labels that each got.

#205 Autoformat with black and isort
  .github/workflows/lint.yml
  aslprep/__about__.py
  aslprep/__init__.py
  aslprep/__main__.py
  aslprep/_warnings.py
  aslprep/cli/aggregate_qc.py
  aslprep/cli/parser.py
  aslprep/cli/run.py
  aslprep/cli/tests/__init__.py
  aslprep/cli/version.py
  aslprep/cli/workflow.py
  aslprep/config.py
  aslprep/interfaces/__init__.py
  aslprep/interfaces/cbf_computation.py
  aslprep/interfaces/confounds.py
  aslprep/interfaces/multiecho.py
  aslprep/interfaces/reports.py
  aslprep/tests/test_config.py
  aslprep/tests/test_confounds.py
  aslprep/tests/test_parser.py
  aslprep/tests/test_version.py
  aslprep/tests/testing.py
  aslprep/tests/tests.py
  aslprep/tests/utils.py
  aslprep/utils/bids.py
  aslprep/utils/meepi.py
  aslprep/utils/misc.py
  aslprep/utils/sentry.py
  aslprep/workflows/asl/__init__.py
  aslprep/workflows/asl/base.py
  aslprep/workflows/asl/cbf.py
  aslprep/workflows/asl/confounds.py
  aslprep/workflows/asl/ge_utils.py
  aslprep/workflows/asl/gecbf.py
  aslprep/workflows/asl/hmc.py
  aslprep/workflows/asl/outputs.py
  aslprep/workflows/asl/registration.py
  aslprep/workflows/asl/resampling.py
  aslprep/workflows/asl/stc.py
  aslprep/workflows/asl/t2s.py
  aslprep/workflows/asl/tests/__init__.py
  aslprep/workflows/base.py
  pyproject.toml
  setup.cfg
Labels: maintenance

#208 Rename PEP8-noncompliant classes
  aslprep/interfaces/cbf_computation.py
  aslprep/interfaces/confounds.py
  aslprep/interfaces/multiecho.py
  aslprep/interfaces/reports.py
  aslprep/tests/test_confounds.py
  aslprep/workflows/asl/base.py
  aslprep/workflows/asl/cbf.py
  aslprep/workflows/asl/confounds.py
  aslprep/workflows/asl/ge_utils.py
  aslprep/workflows/asl/gecbf.py
  aslprep/workflows/asl/outputs.py
  aslprep/workflows/asl/t2s.py
Labels: refactor

#209 Consistently use f-strings for string formatting
  aslprep/__about__.py
  aslprep/__main__.py
  aslprep/cli/parser.py
  aslprep/cli/run.py
  aslprep/cli/version.py
  aslprep/config.py
  aslprep/interfaces/cbf_computation.py
  aslprep/interfaces/reports.py
  aslprep/utils/bids.py
  aslprep/utils/sentry.py
  aslprep/workflows/asl/base.py
  aslprep/workflows/asl/cbf.py
  aslprep/workflows/asl/ge_utils.py
  aslprep/workflows/asl/gecbf.py
  aslprep/workflows/asl/outputs.py
  aslprep/workflows/asl/registration.py
  aslprep/workflows/asl/resampling.py
  aslprep/workflows/asl/stc.py
  aslprep/workflows/base.py
Labels: refactor

#211 Pin looseversion
  setup.cfg
Labels: bug

#210 Work on fixing docstrings and splitting modules
  aslprep/__init__.py
  aslprep/__main__.py
  aslprep/cli/__init__.py
  aslprep/cli/aggregate_qc.py
  aslprep/cli/workflow.py
  aslprep/config.py
  aslprep/data/boilerplate.bib
  aslprep/data/boilerplate3.bib
  aslprep/interfaces/__init__.py
  aslprep/interfaces/bids.py
  aslprep/interfaces/cbf_computation.py
  aslprep/interfaces/confounds.py
  aslprep/interfaces/ge.py
  aslprep/interfaces/multiecho.py
  aslprep/interfaces/plotting.py
  aslprep/interfaces/reports.py
  aslprep/niworkflows/interfaces/plotting.py
  aslprep/niworkflows/viz/plots.py
  aslprep/niworkflows/viz/utils.py
  aslprep/utils/bids.py
  aslprep/utils/confounds.py
  aslprep/utils/meepi.py
  aslprep/utils/misc.py
  aslprep/utils/plotting.py
  aslprep/utils/qc.py
  aslprep/workflows/__init__.py
  aslprep/workflows/asl/__init__.py
  aslprep/workflows/asl/base.py
  aslprep/workflows/asl/cbf.py
  aslprep/workflows/asl/confounds.py
  aslprep/workflows/asl/ge_utils.py
  aslprep/workflows/asl/gecbf.py
  aslprep/workflows/asl/hmc.py
  aslprep/workflows/asl/outputs.py
  aslprep/workflows/asl/registration.py
  aslprep/workflows/asl/resampling.py
  aslprep/workflows/asl/stc.py
  aslprep/workflows/asl/t2s.py
  aslprep/workflows/base.py
  docs/conf.py
  setup.cfg
Labels: maintenance

#212 Remove unused arguments throughout package
  aslprep/utils/bids.py
  aslprep/utils/misc.py
  aslprep/utils/plotting.py
  aslprep/workflows/asl/base.py
  aslprep/workflows/asl/cbf.py
  aslprep/workflows/asl/confounds.py
  aslprep/workflows/asl/ge_utils.py
  aslprep/workflows/asl/gecbf.py
  aslprep/workflows/asl/registration.py
  aslprep/workflows/asl/t2s.py
  setup.cfg
Labels: maintenance

#192 FIX: Update ordering of probseg maps
  aslprep/smriprep/data/io_spec.json
Labels: bug

#216 Rename BIDS-noncompliant derivatives
  aslprep/niworkflows/data/nipreps.json
  aslprep/tests/data/test_outputs_sub01.txt
  aslprep/tests/data/test_outputs_subA00086748.txt
  aslprep/workflows/asl/outputs.py
  docs/outputs.rst
Labels: bug, breaking-change

#217 Replace smriprep calls with dependency calls
  aslprep/interfaces/reports.py
  aslprep/niworkflows/viz/utils.py
  aslprep/smriprep/__about__.py
  aslprep/smriprep/__init__.py
  aslprep/smriprep/__main__.py
  aslprep/smriprep/_version.py
  aslprep/smriprep/conf/__init__.py
  aslprep/smriprep/data/boilerplate.bib
  aslprep/smriprep/data/io_spec.json
  aslprep/smriprep/data/itkIdentityTransform.txt
  aslprep/smriprep/data/tests/dataset_description.json
  aslprep/smriprep/interfaces/__init__.py
  aslprep/smriprep/interfaces/freesurfer.py
  aslprep/smriprep/interfaces/reports.py
  aslprep/smriprep/interfaces/templateflow.py
  aslprep/smriprep/utils/__init__.py
  aslprep/smriprep/utils/bids.py
  aslprep/smriprep/utils/misc.py
  aslprep/smriprep/workflows/__init__.py
  aslprep/smriprep/workflows/anatomical.py
  aslprep/smriprep/workflows/base.py
  aslprep/smriprep/workflows/norm.py
  aslprep/smriprep/workflows/outputs.py
  aslprep/smriprep/workflows/surfaces.py
  aslprep/workflows/asl/outputs.py
  aslprep/workflows/base.py
  docs/workflows.rst
  setup.cfg
Labels: refactor, maintenance

#220 Use custom formatting for workflow connections
  aslprep/tests/utils.py
  aslprep/workflows/asl/base.py
  aslprep/workflows/asl/cbf.py
  aslprep/workflows/asl/confounds.py
  aslprep/workflows/asl/ge_utils.py
  aslprep/workflows/asl/gecbf.py
  aslprep/workflows/asl/hmc.py
  aslprep/workflows/asl/outputs.py
  aslprep/workflows/asl/registration.py
  aslprep/workflows/asl/resampling.py
  aslprep/workflows/asl/stc.py
  aslprep/workflows/asl/t2s.py
  aslprep/workflows/base.py
Labels: refactor

#223 Add custom release notes config file
  .github/release.yml
Labels: ignore-for-release, maintenance

#224 Add CFF file
  CITATION.cff
Labels: ignore-for-release, maintenance

#225 Add ASLPrep DOIs to README and boilerplate
  README.rst
  aslprep/data/boilerplate.bib
  aslprep/workflows/base.py
  docs/workflows.rst
Labels: ignore-for-release, maintenance
