Repository PennLINC/aslprep, pull requests merged in 2025-05, with the labels that each got.

#510 Bring ASLPrep in line with fMRIPrep 25.0.0
  aslprep/cli/parser.py
  aslprep/config.py
  aslprep/data/io_spec.json
  aslprep/data/reports-spec-asl.yml
  aslprep/data/reports-spec.yml
  aslprep/interfaces/confounds.py
  aslprep/interfaces/reports.py
  aslprep/tests/data/config.toml
  aslprep/tests/data/expected_outputs_examples_pcasl_singlepld_siemens.txt
  aslprep/tests/data/expected_outputs_qtab.txt
  aslprep/tests/data/expected_outputs_test_003_minimal.txt
  aslprep/tests/data/expected_outputs_test_003_resampling.txt
  aslprep/tests/test_cli.py
  aslprep/utils/bids.py
  aslprep/workflows/asl/apply.py
  aslprep/workflows/asl/base.py
  aslprep/workflows/asl/confounds.py
  aslprep/workflows/asl/fit.py
  aslprep/workflows/asl/outputs.py
  aslprep/workflows/base.py
  docs/_static/sub-01.html
  docs/_static/sub-01/figures/sub-01_desc-about_T1w.html
  pyproject.toml
Labels: maintenance, nipreps

#518 fix: Find aslrefs in precomputed derivatives, remove bad connection
  aslprep/cli/run.py
  aslprep/data/fmap_spec.json
  aslprep/data/io_spec.json
  aslprep/workflows/asl/fit.py
  aslprep/workflows/base.py
Labels: bug

#524 Add boilerplate elements to templates
  aslprep/data/reports-spec-anat.yml
  aslprep/data/reports-spec.yml
Labels: bug

#525 FIX: Change MCFLIRT cost function to Mutual Information
  aslprep/workflows/asl/hmc.py
Labels: bug

#526 Remove dummy scan-related code
  aslprep/cli/parser.py
  aslprep/config.py
  aslprep/interfaces/cbf.py
  aslprep/interfaces/confounds.py
  aslprep/interfaces/reports.py
  aslprep/tests/data/config.toml
  aslprep/workflows/asl/base.py
  aslprep/workflows/asl/cbf.py
  aslprep/workflows/asl/confounds.py
  aslprep/workflows/asl/fit.py
  aslprep/workflows/asl/plotting.py
  aslprep/workflows/asl/reference.py
  docs/workflows.rst
Labels: maintenance

#531 rf: Split fieldmap registration into its own fit step
  aslprep/workflows/asl/fit.py
  pyproject.toml
Labels: refactor

#535 Speed up integration tests
  .circleci/config.yml
  aslprep/tests/data/expected_outputs_examples_pcasl_multipld.txt
  aslprep/tests/data/expected_outputs_examples_pcasl_singlepld_ge.txt
  aslprep/tests/data/expected_outputs_examples_pcasl_singlepld_siemens.txt
  aslprep/tests/data/expected_outputs_qtab.txt
  aslprep/tests/data/expected_outputs_test_001.txt
  aslprep/tests/data/expected_outputs_test_002.txt
  aslprep/tests/data/expected_outputs_test_003.txt
  aslprep/tests/data/expected_outputs_test_003_full.txt
  aslprep/tests/data/expected_outputs_test_003_minimal.txt
  aslprep/tests/data/expected_outputs_test_003_resampling.txt
  aslprep/tests/test_cli.py
  aslprep/tests/utils.py
Labels: testing

#533 Clarify cli help messages
  aslprep/cli/parser.py
Labels: documentation

#543 Speed up FreeSurfer BBR in the CI tests
  aslprep/tests/test_cli.py
  aslprep/tests/utils.py
  aslprep/workflows/asl/fit.py
Labels: testing

#542 Use Gaussian interpolation for resampling tissue probability maps
  aslprep/workflows/asl/cbf.py
Labels: enhancement, nipreps

#537 Replace BOLD and EPI with ASL in code
  aslprep/cli/parser.py
  aslprep/cli/workflow.py
  aslprep/config.py
  aslprep/data/reports-spec-asl.yml
  aslprep/data/reports-spec.yml
  aslprep/interfaces/plotting.py
  aslprep/workflows/asl/apply.py
  aslprep/workflows/asl/base.py
  aslprep/workflows/asl/confounds.py
  aslprep/workflows/asl/fit.py
  aslprep/workflows/asl/outputs.py
  aslprep/workflows/asl/reference.py
  aslprep/workflows/asl/resampling.py
  aslprep/workflows/base.py
Labels: documentation

#529 Fix typos in documentation and add page on BIDS curation
  README.rst
  docs/bids.rst
  docs/index.rst
  docs/outputs.rst
  docs/usage.rst
  docs/workflows.rst
Labels: documentation

#547 Add figure plotting brain mask
  aslprep/data/aslprep_bids_config.json
  aslprep/data/reports-spec-asl.yml
  aslprep/data/reports-spec.yml
  aslprep/interfaces/plotting.py
  aslprep/tests/test_cli.py
  aslprep/utils/plotting.py
  aslprep/workflows/asl/base.py
  aslprep/workflows/asl/confounds.py
Labels: enhancement

#556 Resample M0 scan to ASL resolution
  aslprep/data/reports-spec-asl.yml
  aslprep/data/reports-spec.yml
  aslprep/interfaces/utility.py
  aslprep/workflows/asl/fit.py
  aslprep/workflows/asl/hmc.py
Labels: bug
